vignettes/DALEX_and_xgboost.Rmd

variable_dropout() -> variable_importance()
single_variable() -> variable_response()
single_prediction() -> prediction_breakdown()

Update function names in vignette

---

R/yhat.R

Added yhat functions for glmnet and cv.glmnet
See #64

Fixing compatibility with glmnet

---

R/explain.R

Although it is written in the documentation, this part can be confusing for some users (tested on students). After this change, explain() will print a message when the user passes a factor/character vector as y in case of binary classification.

adds message for as.factor(y) = T

---

python/dalex/dalex/dataset_level/aggregated_profiles/aggregated_profiles.py
python/dalex/dalex/dataset_level/aggregated_profiles/checks.py
python/dalex/dalex/dataset_level/aggregated_profiles/utils.py
python/dalex/dalex/dataset_level/model_performance/model_performance.py
python/dalex/dalex/dataset_level/model_performance/utils.py
python/dalex/dalex/dataset_level/variable_importance/loss_functions.py
python/dalex/dalex/dataset_level/variable_importance/utils.py
python/dalex/dalex/dataset_level/variable_importance/variable_importance.py
python/dalex/dalex/explainer/checks.py
python/dalex/dalex/explainer/helper.py
python/dalex/dalex/explainer/theme.py
python/dalex/dalex/instance_level/break_down/break_down.py
python/dalex/dalex/instance_level/break_down/utils.py
python/dalex/dalex/instance_level/ceteris_paribus/ceteris_paribus.py
python/dalex/dalex/instance_level/shap/shap.py
python/dalex/dalex/instance_level/shap/utils.py

- change numeric detection from `not pd.api.types.is_string_dtype(x)` to 
`np.issubdtype(x.dtype, np.number)` since the first gives `True` to `bool` etc.
- change `explainer.predict_function(explainer.model, explainer.data)` to
`explainer.predict(explainer.data)`
- safer calculation of measures
- plot code refactoring
- add color function
- add legend for AP plot
- fix wrong definition of residual_function
- add residuals df to ModelPerformance
- add basic plot for ModelPerformance

[python] fix residuals, add plot and more

---

.Rbuildignore
R/explain.R
R/misc_yhat.R
R/plot_model_performance.R
tests/testthat/test_explain.R

Candidate fix for #163 #156 and #155

Issue #163 #156 #155

---

python/dalex/NEWS.md
python/dalex/dalex/_explainer/checks.py
python/dalex/dalex/_explainer/object.py
python/dalex/dalex/instance_level/_shap/utils.py

* added `dump` and `dumps` methods for saving explainer in a binary form
* added `load` and `loads` methods for loading explainer from binary form
* changed `B:=B+1` in shap
* fixed printing in Explainer constructor

[python] Dump and load, shap B

---

python/dalex/NEWS.md
python/dalex/dalex/_explainer/object.py
python/dalex/dalex/instance_level/_break_down/utils.py
python/dalex/dalex/instance_level/_shap/object.py
python/dalex/dalex/instance_level/_shap/plot.py
python/dalex/dalex/instance_level/_shap/utils.py
python/dalex/setup.py

fixes `Shap`, fixes `Shap.plot`, fixes #180

[python] dalex v0.1.4

---

python/dalex/NEWS.md
python/dalex/README.md
python/dalex/dalex/dataset_level/_aggregated_profiles/object.py
python/dalex/dalex/dataset_level/_model_performance/object.py
python/dalex/dalex/dataset_level/_variable_importance/object.py
python/dalex/dalex/instance_level/_break_down/object.py
python/dalex/dalex/instance_level/_ceteris_paribus/object.py
python/dalex/dalex/instance_level/_shap/object.py

[python] add in code figure saving

---

python/dalex/NEWS.md
python/dalex/dalex/instance_level/_break_down/checks.py
python/dalex/dalex/instance_level/_ceteris_paribus/checks.py
python/dalex/dalex/instance_level/_ceteris_paribus/object.py
python/dalex/dalex/instance_level/_shap/checks.py
python/dalex/setup.py

fixes #211 imo after these bugfixes it's ready for pypi

[python] dalex v0.1.6

---

python/dalex/NEWS.md
python/dalex/dalex/_explainer/checks.py
python/dalex/dalex/dataset_level/_aggregated_profiles/checks.py

[python] fix model_profile calculation and numpy defaults

---

python/dalex/NEWS.md
python/dalex/dalex/_explainer/checks.py
python/dalex/dalex/_explainer/object.py
python/dalex/dalex/dataset_level/_aggregated_profiles/checks.py
python/dalex/dalex/dataset_level/_aggregated_profiles/object.py
python/dalex/dalex/dataset_level/_aggregated_profiles/utils.py
python/dalex/dalex/dataset_level/_variable_importance/utils.py
python/dalex/dalex/instance_level/_shap/utils.py
python/dalex/test/test_aggregated_profiles.py
python/dalex/test/test_feature_importance.py
python/dalex/test/test_model_performance.py
python/dalex/test/test_predict.py
python/dalex/test/test_predict_parts.py

* fixed `label` and `group` in `model_profile` (wrong labelling with groups and an error with grouping `ale` and `cond`
* if `N` is `None` then take all observations
* added tests for `model_parts`
* added test for `feature_importance`
* added test for `model_performance`
* added test for `predict`
* added test for `predict_parts`
* normalized input for `model_parts`
* added checks for predict and `predict_parts`

[python] fixed label and group in model_profile

---

python/dalex/NEWS.md
python/dalex/dalex/_explainer/checks.py
python/dalex/dalex/_explainer/object.py
python/dalex/dalex/dataset_level/_variable_importance/checks.py
python/dalex/dalex/instance_level/_break_down/checks.py
python/dalex/dalex/instance_level/_ceteris_paribus/checks.py
python/dalex/dalex/instance_level/_ceteris_paribus/object.py
python/dalex/dalex/instance_level/_shap/checks.py
python/dalex/setup.py
python/dalex/test/test_feature_importance.py

* parameter `variable_splits` did not work in `predict_profiles`
* minor fixes in checks in `individual_profile`
* more readable printing while constructing explainer

[python] fix variable_splits and upgrade checks

---

python/dalex/NEWS.md
python/dalex/dalex/dataset_level/_aggregated_profiles/object.py
python/dalex/dalex/dataset_level/_variable_importance/object.py

[python] fix baseline in AP plot

---

python/dalex/dalex/_explainer/object.py
python/dalex/test/test_aggregated_profiles.py
python/dalex/test/test_model_performance.py
python/dalex/test/test_predict_parts.py

#161 
Changes in predict_parts tests are mostly due to the automatic code refactoring.

[python] finish tests

---

python/dalex/NEWS.md
python/dalex/dalex/_explainer/object.py
python/dalex/dalex/dataset_level/_aggregated_profiles/object.py
python/dalex/dalex/dataset_level/_aggregated_profiles/utils.py
python/dalex/dalex/dataset_level/_variable_importance/checks.py
python/dalex/dalex/dataset_level/_variable_importance/object.py
python/dalex/dalex/dataset_level/_variable_importance/utils.py
python/dalex/dalex/instance_level/_break_down/checks.py
python/dalex/dalex/instance_level/_ceteris_paribus/checks.py
python/dalex/dalex/instance_level/_ceteris_paribus/object.py
python/dalex/dalex/instance_level/_ceteris_paribus/utils.py
python/dalex/dalex/instance_level/_shap/checks.py
python/dalex/dalex/instance_level/_shap/object.py
python/dalex/dalex/instance_level/_shap/utils.py
python/dalex/test/test_aggregated_profiles.py
python/dalex/test/test_ceteris_paribus.py
python/dalex/test/test_model_performance.py
python/dalex/test/test_predict_parts.py
python/dalex/test/test_variable_importance.py

* *feature:* multiprocessing added for: `model_profile`, `model_parts`, `model_profile` and `shap`
* *fix:* significantly improved speed of "accumulated local effects" and "conditional" in `model_profile`

[python] Multiprocessing added

---

python/dalex/NEWS.md
python/dalex/dalex/dataset_level/_variable_importance/object.py
python/dalex/dalex/dataset_level/_variable_importance/plot.py
python/dalex/dalex/instance_level/_break_down/object.py
python/dalex/dalex/instance_level/_break_down/plot.py
python/dalex/dalex/instance_level/_ceteris_paribus/utils.py
python/dalex/dalex/instance_level/_shap/object.py
python/dalex/dalex/instance_level/_shap/plot.py

closes #245 ; fixes CP/AP for lightgbm fifa example

[python] fix label rounding

---

python/dalex/NEWS.md
python/dalex/dalex/_explainer/object.py
python/dalex/dalex/dataset_level/_aggregated_profiles/object.py
python/dalex/dalex/dataset_level/_variable_importance/checks.py
python/dalex/dalex/dataset_level/_variable_importance/object.py
python/dalex/dalex/instance_level/_shap/checks.py
python/dalex/dalex/instance_level/_shap/object.py
python/dalex/setup.py

* *feature:* added `random_state` parameter for `SHAP` and `model_profile` for reproducible calculations
* *fix:* fixed `random_state` parameter in `model_parts`

[Python] new version: 0.1.9, added and fixed random states

---

NEWS.md
R/misc_loss_functions.R
R/model_profile.R
R/model_variable_effect.R
R/predict_parts.R
man/model_profile.Rd
man/predict_parts.Rd
man/variable_effect.Rd

Add attributes to loss_functions

---

DESCRIPTION
NEWS.md
R/explain.R
R/misc_loss_functions.R
R/model_performance.R

closes #281 closes #282 closes #284

[r] update dependencies and error printing

---

NEWS.md
R/explain.R
R/misc_yhat.R
README.md
man/explain.Rd
tests/testthat/test_explain.R
tests/testthat/test_yhat_model_info.R

https://github.com/ModelOriented/DALEX/issues/309
https://github.com/ModelOriented/DALEX/issues/231

Candidate fix for Issue #231 and #309

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
NEWS.md
R/model_profile.R
R/model_variable_effect.R
tests/testthat/helper-objects.R

[r] deprecated

---

DESCRIPTION
NEWS.md
R/misc.R
R/model_diagnostics.R
tests/testthat/test_model_diagnostics.R

[r] fix errors when using dx.Explainer

---

.github/workflows/test-coverage.yaml

there was a bug related to not installing required imports by githubactions.

Codecov fix

---

vignettes/multilabel_classification.Rmd

added some suggestions to vignette about multilabel classification

added some suggestions to vignette

---

NEWS.md
R/explain.R
tests/testthat/test_explain.R

Logical values in y rise unnecessary error for classification task. Related to https://github.com/ModelOriented/DALEX/issues/336

Logical values in y rise unnecessery error

---

DESCRIPTION
NEWS.md
R/explain.R
R/misc_yhat.R
R/model_info.R
man/explain.Rd
tests/external_tests/external_test_yhat_model_info.R
tests/testthat/test_explain.R

Issue #250 v2

---

.gitignore
python/dalex/NEWS.md
python/dalex/dalex/__init__.py
python/dalex/dalex/_explainer/checks.py
python/dalex/dalex/_explainer/object.py
python/dalex/dalex/_explainer/yhat.py
python/dalex/dalex/_global_checks.py
python/dalex/dalex/dataset_level/_aggregated_profiles/object.py
python/dalex/dalex/fairness/_group_fairness/utils.py
python/dalex/dalex/wrappers/_shap/checks.py
python/dalex/setup.py

mentions #332
changes in `NEWS.md`
notebook with a simple example (later to become part of docs): [h2o.zip](https://github.com/ModelOriented/DALEX/files/5593134/h2o.zip)
Bear in mind that `h2o` is prone to errors - depends on OS. This will work but could be slow because of the data conversions and lengthy predict requests (same like in R DALEXtra).

[python] add h2o, code maintenance

---

python/dalex/NEWS.md
python/dalex/dalex/arena/object.py
python/dalex/dalex/arena/plots/__init__.py
python/dalex/dalex/arena/plots/_fairness_check_container.py
python/dalex/dalex/arena/server.py
python/dalex/test/test_arena_classification.py

Adds Fairness Check to Arena module.
Example usage is in notebook https://gist.github.com/piotrpiatyszek/86f3eb5d749c6a9dabcf75ab7f325917

[Pyton][Arena] Add Fairnes plot

---

python/dalex/NEWS.md
python/dalex/dalex/__init__.py
python/dalex/dalex/fairness/_group_fairness/plot.py

* fixed broken range on `yaxis` in `fairness_check` plot ([#376](https://github.com/ModelOriented/DALEX/issues/376))

[python][fairness] Fix Issue #376

---

python/dalex/NEWS.md
python/dalex/README.md
python/dalex/dalex/__init__.py
python/dalex/dalex/_explainer/checks.py
python/dalex/dalex/documentation.md
tox.ini

[python] dalex v1.0.1

---

python/dalex/dalex/model_explanations/_variable_importance/object.py
python/dalex/dalex/model_explanations/_variable_importance/utils.py
python/dalex/dalex/predict_explanations/_shap/object.py
python/dalex/dalex/predict_explanations/_shap/utils.py
python/dalex/test/test_variable_importance.py

Fixes #392 problem with equal seeds in multiprocessing using `SeesSequence` https://numpy.org/doc/stable/reference/random/parallel.html

[python] issue #392 fix

---

python/dalex/NEWS.md
python/dalex/dalex/fairness/_group_fairness/plot.py
python/dalex/dalex/fairness/_group_fairness/utils.py

[python] Issue #409

---

python/dalex/NEWS.md
python/dalex/dalex/model_explanations/_variable_importance/utils.py
python/dalex/dalex/predict_explanations/_ceteris_paribus/utils.py
python/dalex/dalex/predict_explanations/_shap/utils.py

Enforce multiprocessing context to 'spawn'

---

python/dalex/NEWS.md
python/dalex/dalex/fairness/_group_fairness/plot.py

[python][fairness] metric_scores plot axis fix (#416)

---

python/dalex/NEWS.md
python/dalex/dalex/__init__.py
python/dalex/dalex/fairness/__init__.py
python/dalex/dalex/fairness/_basics/checks.py
python/dalex/dalex/fairness/_group_fairness/checks.py
python/dalex/dalex/fairness/_group_fairness/mitigation.py
python/dalex/dalex/fairness/_group_fairness/utils.py
python/dalex/test/test_fairness.py
python/dalex/test/test_shap_wrapper.py

Issue #432

---

.github/workflows/R-CMD-check.yaml
DESCRIPTION
NEWS.md
R/model_info.R
man/model_info.Rd

A quick fix to the documentation. Not the list of supported packages properly goes to the details section

Fix model_info documentation

---

python/dalex/NEWS.md
python/dalex/dalex/arena/server.py
python/dalex/test/test_arena_classification.py

Arena now manually starts WSGI server instead of using Flask method.
Having an instance of this server, we can close without using the old deprecated method with env variables.

Issue #518 - stopping Arena's werkzeug server

---

python/dalex/dalex/aspect/utils.py

Fixes #537 as described in the same issue.

Replace NaN values in depend matrix

---

python/dalex/NEWS.md
python/dalex/dalex/arena/plots/__init__.py
python/dalex/dalex/arena/plots/_variable_against_another_container.py
python/dalex/dalex/arena/plots/_variable_distribution_container.py
python/dalex/test/test_arena_classification.py

Fix missing EDA plots in (Python) Arena

---

python/dalex/dalex/predict_explanations/_ceteris_paribus/utils.py

Fixing the issue described in #550.

Fix MultiIndex Pandas DataFrame issue
